# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-18 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippets',
            name='syntax_type',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
    ]
